### ISSUE TITLE
Is there a performance comparison of yolov10 in trt and deepstream? When will it support aqt?

### ISSUE THREAD

**Issue by tms2003** [levipereira/deepstream-yolo-e2e#3]
Is there a performance comparison of yolov10 in trt and deepstream? When will it support aqt?

**Comment by levipereira** [comment]
There is no difference between YOLOv10 in TRT and DeepStream, as DeepStream uses TRT as its backend. However, DeepStream includes various GPU-accelerated components, including the YOLOv10 model with TRT. If you want to optimize the performance of the entire pipeline, please refer to  this [configuration](https://github.com/levipereira/deepstream-yolo-e2e/blob/master/deepstream_yolo_det.txt#L2)

I have the QAT ready, but the problem is implementing it with the DataLoader and model evaluation. At the moment, I don't have the time for that.
